# Generated by Django 5.0.6 on 2024-06-30 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('optional_dead_date', models.DateTimeField(blank=True, null=True)),
                ('boolean_field', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(blank=True, to='list.tag')),
            ],
        ),
    ]
