# Generated by Django 5.0.6 on 2024-07-01 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='datetime',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='optional_dead_date',
            new_name='deadline',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='boolean_field',
            new_name='is_done',
        ),
        migrations.AlterField(
            model_name='task',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='tasks', to='list.tag'),
        ),
    ]
