# Generated by Django 5.0.6 on 2024-07-01 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_alter_task_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='task',
            options={'ordering': ['is_done', '-created_at']},
        ),
    ]
